package com.zark.sbproject.boot.dao.common.mapper;

import com.zark.sbproject.boot.dao.common.entity.LockPO;
import com.zark.sbproject.boot.dao.common.entity.LockPOExample;
import java.util.List;

public interface LockPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_lock
     *
     * @mbg.generated Sat Aug 24 14:28:49 CST 2019
     */
    long countByExample(LockPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_lock
     *
     * @mbg.generated Sat Aug 24 14:28:49 CST 2019
     */
    int deleteByPrimaryKey(LockPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_lock
     *
     * @mbg.generated Sat Aug 24 14:28:49 CST 2019
     */
    int insertSelective(LockPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_lock
     *
     * @mbg.generated Sat Aug 24 14:28:49 CST 2019
     */
    List<LockPO> selectByExample(LockPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_lock
     *
     * @mbg.generated Sat Aug 24 14:28:49 CST 2019
     */
    LockPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_lock
     *
     * @mbg.generated Sat Aug 24 14:28:49 CST 2019
     */
    int updateByPrimaryKeySelective(LockPO record);
}