package com.zark.sbproject.boot.dao.common.mapper;

import com.zark.sbproject.boot.dao.common.entity.MessageDealPO;
import com.zark.sbproject.boot.dao.common.entity.MessageDealPOExample;
import java.util.List;

public interface MessageDealPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_message_deal
     *
     * @mbg.generated Sat Aug 24 14:28:49 CST 2019
     */
    long countByExample(MessageDealPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_message_deal
     *
     * @mbg.generated Sat Aug 24 14:28:49 CST 2019
     */
    int deleteByPrimaryKey(MessageDealPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_message_deal
     *
     * @mbg.generated Sat Aug 24 14:28:49 CST 2019
     */
    int insertSelective(MessageDealPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_message_deal
     *
     * @mbg.generated Sat Aug 24 14:28:49 CST 2019
     */
    List<MessageDealPO> selectByExample(MessageDealPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_message_deal
     *
     * @mbg.generated Sat Aug 24 14:28:49 CST 2019
     */
    MessageDealPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_message_deal
     *
     * @mbg.generated Sat Aug 24 14:28:49 CST 2019
     */
    int updateByPrimaryKeySelective(MessageDealPO record);
}