package com.zark.sbproject.boot.dao.user.mapper;

import com.zark.sbproject.boot.dao.user.entity.UserPO;
import com.zark.sbproject.boot.dao.user.entity.UserPOExample;
import java.util.List;

public interface UserPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zark_user
     *
     * @mbg.generated Sat Aug 24 01:42:21 CST 2019
     */
    long countByExample(UserPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zark_user
     *
     * @mbg.generated Sat Aug 24 01:42:21 CST 2019
     */
    int deleteByPrimaryKey(UserPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zark_user
     *
     * @mbg.generated Sat Aug 24 01:42:21 CST 2019
     */
    int insertSelective(UserPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zark_user
     *
     * @mbg.generated Sat Aug 24 01:42:21 CST 2019
     */
    List<UserPO> selectByExample(UserPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zark_user
     *
     * @mbg.generated Sat Aug 24 01:42:21 CST 2019
     */
    UserPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zark_user
     *
     * @mbg.generated Sat Aug 24 01:42:21 CST 2019
     */
    int updateByPrimaryKeySelective(UserPO record);
}