@startuml
User --> (KO)
User --> (设计评审)
User --> (开发计划)
User --> (TC评审)
User --> (提测)
User --> (发布评审)
User --> (UAT验证)
User --> (发布)

(KO)-->(外部资源整合)
    (外部资源整合)-->(前端资源)
    (外部资源整合)-->(测试资源)
(KO)-->(里程碑)

(设计评审)-->(架构图)
(设计评审)-->(数据模型)
(设计评审)-->(系统难点设计)
(设计评审)-->(关键业务时序图)

(开发计划)-->(项目搭建)
(开发计划)-->(模块里程碑)
(开发计划)-->(BUFFER)
(开发计划)-->(自测)
(开发计划)-->(联调)

(提测)-->(冒烟)
(提测)-->(测试)

(发布)-->(发布方案)
(发布)-->(回滚方案)
(发布)-->(工具准备)
(发布)-->(环境装备)
    (环境装备)-->(配置)
    (环境装备)-->(权限)
    (环境装备)-->(数据库)
(发布)-->(上下游系统发布)
(发布)-->(验证)

@enduml

